steps:
  - name: 'gcr.io/cloud-builders/npm'
    id: Install dependencies
    args: ['install']

  - name: 'gcr.io/cloud-builders/docker'
    id: Build image
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/swanners-backend:$SHORT_SHA',
        '-t',
        'gcr.io/$PROJECT_ID/swanners-backend:lastest',
        '.',
      ]

  - name: 'gcr.io/cloud-builders/npm'
    id: Migration
    args: ['npm', 'run', 'migration']
    env:
      - 'DATABASE_URL=$_DATABASE_URL'

  - name: 'gcr.io/cloud-builders/docker'
    id: Push image
    args: ['push', 'gcr.io/$PROJECT_ID/swanners-backend']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy cloud run
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'swanners-backend',
        '--image',
        'gcr.io/$PROJECT_ID/swanners-backend',
        '--region',
        'asia-southeast1',
        '--platform',
        'managed',
      ]

images: ['gcr.io/$PROJECT_ID/swanners-backend']
