steps:
  - id: Install dependencies
    name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  - id: Build image
    name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/swanners-backend:$SHORT_SHA',
        '-t',
        'gcr.io/$PROJECT_ID/swanners-backend:lastest',
        '.',
      ]

  - id: Install Cloud SQL proxy
    name: alpine:3.10
    entrypoint: sh
    args:
      - -c
      - 'wget -O /workspace/cloud_sql_proxy https://storage.googleapis.com/cloudsql-proxy/v1.16/cloud_sql_proxy.linux.386 &&  chmod +x /workspace/cloud_sql_proxy'

  - id: Migration
    name: 'gcr.io/cloud-builders/npm'
    entrypoint: sh
    args:
      [
        '-c',
        '(/workspace/cloud_sql_proxy -dir=/cloudsql -instances=$_CONNECTION_NAME & sleep 2) && npm run migration',
      ]
    env:
      - 'DATABASE_URL=$_DATABASE_URL'

  - id: Push image
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/swanners-backend']

  - id: Deploy cloud run
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'swanners-backend',
        '--image',
        'gcr.io/$PROJECT_ID/swanners-backend',
        '--region',
        'asia-southeast1',
        '--platform',
        'managed',
      ]

images: ['gcr.io/$PROJECT_ID/swanners-backend']
